# Generated by Django 3.1.5 on 2021-01-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='item',
            name='album',
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
