# Generated by Django 3.1.5 on 2021-01-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
