# Generated by Django 3.1.5 on 2021-01-06 15:19

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210106_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=djrichtextfield.models.RichTextField(null=True, verbose_name='Описание'),
        ),
    ]
